# Generated by Django 4.2.9 on 2025-12-06 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Trip date")),
                (
                    "start_address",
                    models.CharField(
                        help_text="Starting location address", max_length=500
                    ),
                ),
                (
                    "end_address",
                    models.CharField(help_text="Destination address", max_length=500),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Distance must be positive"
                            ),
                            django.core.validators.MaxValueValidator(
                                9999.99, message="Distance seems unreasonably high"
                            ),
                        ],
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="Trip purpose or description (optional)",
                        max_length=500,
                    ),
                ),
            ],
        ),
    ]
