# Generated by Django 4.2.9 on 2025-12-06 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trip",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Trip",
                "verbose_name_plural": "Trips",
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Entry creation timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="is_manual",
            field=models.BooleanField(
                default=False,
                help_text="True if distance was entered manually (not calculated)",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="route_data",
            field=models.JSONField(
                blank=True,
                help_text="Google Maps API response data (if available)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["user", "date"], name="trips_trip_user_id_ad313f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(fields=["date"], name="trips_trip_date_23da48_idx"),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["user", "-created_at"], name="trips_trip_user_id_2f4a85_idx"
            ),
        ),
    ]
