# Generated by Django 4.2.9 on 2025-12-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Report year (YYYY)")),
                ("month", models.IntegerField(help_text="Report month (1-12)")),
                (
                    "total_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total kilometers for the month",
                        max_digits=10,
                    ),
                ),
                (
                    "trip_count",
                    models.IntegerField(
                        default=0, help_text="Number of trips in this report"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF report file",
                        null=True,
                        upload_to="reports/pdf/",
                    ),
                ),
                (
                    "excel_file",
                    models.FileField(
                        blank=True,
                        help_text="Generated Excel report file",
                        null=True,
                        upload_to="reports/excel/",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, help_text="Email sent timestamp", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Report generation timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Report",
                "verbose_name_plural": "Monthly Reports",
                "ordering": ["-year", "-month"],
            },
        ),
    ]
