# Generated by Django 4.2.9 on 2025-12-06 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyreport",
            name="user",
            field=models.ForeignKey(
                help_text="Report owner",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="monthlyreport",
            index=models.Index(
                fields=["user", "-year", "-month"],
                name="reports_mon_user_id_3aa80c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthlyreport",
            unique_together={("user", "year", "month")},
        ),
    ]
